CHIP		 = LPC11C24FBD48
PORT		 = /dev/cu.usbserial-SL0l841x
#CHIP		 = LPC1114FN28
#PORT		 = /dev/cu.SLAB_USBtoUART
BIN		 = obj/test.bin
SRCS		:= $(abspath $(wildcard *.cpp))
DEFINES		 = scmRTOS_PROCESS_COUNT=1

include $(abspath ../make.inc)
